/**
 * Parse src/assets/sgk-toc-source.txt → src/sgkTocData.js
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const srcPath = path.join(root, 'src', 'assets', 'sgk-toc-source.txt');
const outPath = path.join(root, 'src', 'sgkTocData.js');

function romanToInt(roman) {
  const map = { I: 1, V: 5, X: 10, L: 50, C: 100, D: 500, M: 1000 };
  let result = 0;
  let prev = 0;
  for (let i = roman.length - 1; i >= 0; i--) {
    const val = map[roman[i]] || 0;
    result += val < prev ? -val : val;
    prev = val;
  }
  return result;
}

function parseSgkToc(raw) {
  const lines = String(raw || '')
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n')
    .split('\n');
  const byGrade = {};
  let grade = null;
  let chapter = null;

  for (const line of lines) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    if (/^Tập\s+\d/i.test(t)) continue;
    if (/^Bộ sách:/i.test(t)) continue;
    if (/^MỤC LỤC/i.test(t)) continue;
    if (/^📗/u.test(t) || /^SÁCH GIÁO KHOA/i.test(t)) continue;
    if (/Chương trình mới/i.test(t) && !/^CHƯƠNG/i.test(t)) continue;

    const gm = t.match(/^TOÁN\s+LỚP\s+(\d+)\s*$/i);
    if (gm) {
      grade = gm[1];
      if (!byGrade[grade]) byGrade[grade] = { chapters: [] };
      chapter = null;
      continue;
    }

    const cm = t.match(/^CHƯƠNG\s+([IVXLCDM]+)\.\s*(.+)$/i);
    if (cm && grade) {
      const roman = cm[1].toUpperCase();
      const no = String(romanToInt(roman));
      chapter = {
        no,
        roman,
        title: cm[2].replace(/\.\s*$/, '').trim(),
        lessons: [],
      };
      byGrade[grade].chapters.push(chapter);
      continue;
    }

    const bm = t.match(/^Bài\s+(\d+)\.\s*(.+)$/i);
    if (bm && grade && chapter) {
      chapter.lessons.push({
        no: bm[1],
        title: bm[2].replace(/\.\s*$/, '').trim(),
      });
      continue;
    }

    const om = t.match(/^ÔN\s*TẬP\s+CHƯƠNG\s+([IVXLCDM]+)\.?\s*$/i);
    if (om && grade && chapter) {
      const roman = om[1].toUpperCase();
      chapter.lessons.push({
        no: `OT${romanToInt(roman)}`,
        title: `Ôn tập chương ${roman}`,
        isReview: true,
      });
    }
  }

  return byGrade;
}

const raw = fs.readFileSync(srcPath, 'utf8');
const data = parseSgkToc(raw);
const js = `/** Auto-generated by scripts/build-sgk-toc.mjs — không sửa tay. */\nexport const SGK_TOC_BY_GRADE = ${JSON.stringify(data, null, 2)};\n`;
fs.writeFileSync(outPath, js, 'utf8');
console.log('[build-sgk-toc] Wrote', outPath, 'grades:', Object.keys(data).join(', '));
