/** Auto-generated by scripts/build-sgk-toc.mjs — không sửa tay. */
export const SGK_TOC_BY_GRADE = {
  "6": {
    "chapters": [
      {
        "no": "1",
        "roman": "I",
        "title": "TẬP HỢP CÁC SỐ TỰ NHIÊN",
        "lessons": [
          {
            "no": "1",
            "title": "Tập hợp"
          },
          {
            "no": "2",
            "title": "Cách ghi số tự nhiên"
          },
          {
            "no": "3",
            "title": "Thứ tự trong tập hợp các số tự nhiên"
          },
          {
            "no": "4",
            "title": "Phép cộng và phép trừ số tự nhiên"
          },
          {
            "no": "5",
            "title": "Phép nhân và phép chia số tự nhiên"
          },
          {
            "no": "6",
            "title": "Luỹ thừa với số mũ tự nhiên"
          },
          {
            "no": "7",
            "title": "Thứ tự thực hiện các phép tính"
          },
          {
            "no": "OT1",
            "title": "Ôn tập chương I",
            "isReview": true
          }
        ]
      },
      {
        "no": "2",
        "roman": "II",
        "title": "TÍNH CHIA HẾT TRONG TẬP HỢP CÁC SỐ TỰ NHIÊN",
        "lessons": [
          {
            "no": "8",
            "title": "Quan hệ chia hết và tính chất"
          },
          {
            "no": "9",
            "title": "Dấu hiệu chia hết"
          },
          {
            "no": "10",
            "title": "Số nguyên tố"
          },
          {
            "no": "11",
            "title": "Ước chung. Ước chung lớn nhất"
          },
          {
            "no": "12",
            "title": "Bội chung. Bội chung nhỏ nhất"
          },
          {
            "no": "OT2",
            "title": "Ôn tập chương II",
            "isReview": true
          }
        ]
      },
      {
        "no": "3",
        "roman": "III",
        "title": "SỐ NGUYÊN",
        "lessons": [
          {
            "no": "13",
            "title": "Tập hợp các số nguyên"
          },
          {
            "no": "14",
            "title": "Phép cộng và phép trừ số nguyên"
          },
          {
            "no": "15",
            "title": "Quy tắc dấu ngoặc"
          },
          {
            "no": "16",
            "title": "Phép nhân số nguyên"
          },
          {
            "no": "17",
            "title": "Phép chia hết. Ước và bội của một số nguyên"
          },
          {
            "no": "OT3",
            "title": "Ôn tập chương III",
            "isReview": true
          }
        ]
      },
      {
        "no": "4",
        "roman": "IV",
        "title": "MỘT SỐ HÌNH PHẲNG TRONG THỰC TIỄN",
        "lessons": [
          {
            "no": "18",
            "title": "Hình tam giác đều. Hình vuông. Hình lục giác đều"
          },
          {
            "no": "19",
            "title": "Hình chữ nhật. Hình thoi. Hình bình hành. Hình thang cân"
          },
          {
            "no": "20",
            "title": "Chu vi và diện tích của một số tứ giác đã học"
          },
          {
            "no": "OT4",
            "title": "Ôn tập chương IV",
            "isReview": true
          }
        ]
      },
      {
        "no": "5",
        "roman": "V",
        "title": "TÍNH ĐỐI XỨNG CỦA HÌNH PHẲNG TRONG TỰ NHIÊN",
        "lessons": [
          {
            "no": "21",
            "title": "Hình có trục đối xứng"
          },
          {
            "no": "22",
            "title": "Hình có tâm đối xứng"
          },
          {
            "no": "OT5",
            "title": "Ôn tập chương V",
            "isReview": true
          }
        ]
      },
      {
        "no": "6",
        "roman": "VI",
        "title": "PHÂN SỐ",
        "lessons": [
          {
            "no": "23",
            "title": "Mở rộng phân số. Phân số bằng nhau"
          },
          {
            "no": "24",
            "title": "So sánh phân số. Hỗn số dương"
          },
          {
            "no": "25",
            "title": "Phép cộng và phép trừ phân số"
          },
          {
            "no": "26",
            "title": "Phép nhân và phép chia phân số"
          },
          {
            "no": "27",
            "title": "Hai bài toán về phân số"
          },
          {
            "no": "OT6",
            "title": "Ôn tập chương VI",
            "isReview": true
          }
        ]
      },
      {
        "no": "7",
        "roman": "VII",
        "title": "SỐ THẬP PHÂN",
        "lessons": [
          {
            "no": "28",
            "title": "Số thập phân"
          },
          {
            "no": "29",
            "title": "Tính toán với số thập phân"
          },
          {
            "no": "30",
            "title": "Làm tròn và ước lượng"
          },
          {
            "no": "31",
            "title": "Một số bài toán về tỉ số và tỉ số phần trăm"
          },
          {
            "no": "OT7",
            "title": "Ôn tập chương VII",
            "isReview": true
          }
        ]
      },
      {
        "no": "8",
        "roman": "VIII",
        "title": "NHỮNG HÌNH HỌC CƠ BẢN",
        "lessons": [
          {
            "no": "32",
            "title": "Điểm và đường thẳng"
          },
          {
            "no": "33",
            "title": "Điểm nằm giữa hai điểm. Tia"
          },
          {
            "no": "34",
            "title": "Đoạn thẳng. Độ dài đoạn thẳng"
          },
          {
            "no": "35",
            "title": "Trung điểm của đoạn thẳng"
          },
          {
            "no": "36",
            "title": "Góc"
          },
          {
            "no": "37",
            "title": "Số đo góc"
          },
          {
            "no": "OT8",
            "title": "Ôn tập chương VIII",
            "isReview": true
          }
        ]
      },
      {
        "no": "9",
        "roman": "IX",
        "title": "DỮ LIỆU VÀ XÁC SUẤT THỰC NGHIỆM",
        "lessons": [
          {
            "no": "38",
            "title": "Dữ liệu và thu thập dữ liệu"
          },
          {
            "no": "39",
            "title": "Bảng thống kê và biểu đồ tranh"
          },
          {
            "no": "40",
            "title": "Biểu đồ cột"
          },
          {
            "no": "41",
            "title": "Biểu đồ cột kép"
          },
          {
            "no": "42",
            "title": "Kết quả có thể và sự kiện trong trò chơi, thí nghiệm"
          },
          {
            "no": "43",
            "title": "Xác suất thực nghiệm"
          },
          {
            "no": "OT9",
            "title": "Ôn tập chương IX",
            "isReview": true
          }
        ]
      }
    ]
  },
  "7": {
    "chapters": [
      {
        "no": "1",
        "roman": "I",
        "title": "SỐ HỮU TỈ",
        "lessons": [
          {
            "no": "1",
            "title": "Tập hợp các số hữu tỉ"
          },
          {
            "no": "2",
            "title": "Cộng, trừ, nhân, chia số hữu tỉ"
          },
          {
            "no": "3",
            "title": "Luỹ thừa với số mũ tự nhiên của một số hữu tỉ"
          },
          {
            "no": "4",
            "title": "Thứ tự thực hiện các phép tính. Quy tắc chuyển vế"
          },
          {
            "no": "OT1",
            "title": "Ôn tập chương I",
            "isReview": true
          }
        ]
      },
      {
        "no": "2",
        "roman": "II",
        "title": "SỐ THỰC",
        "lessons": [
          {
            "no": "5",
            "title": "Làm quen với số thập phân vô hạn tuần hoàn"
          },
          {
            "no": "6",
            "title": "Số vô tỉ. Căn bậc hai số học"
          },
          {
            "no": "7",
            "title": "Tập hợp các số thực"
          },
          {
            "no": "OT2",
            "title": "Ôn tập chương II",
            "isReview": true
          }
        ]
      },
      {
        "no": "3",
        "roman": "III",
        "title": "GÓC VÀ ĐƯỜNG THẲNG SONG SONG",
        "lessons": [
          {
            "no": "8",
            "title": "Góc ở vị trí đặc biệt. Tia phân giác của một góc"
          },
          {
            "no": "9",
            "title": "Hai đường thẳng song song và dấu hiệu nhận biết"
          },
          {
            "no": "10",
            "title": "Tiên đề Euclid. Tính chất của hai đường thẳng song song"
          },
          {
            "no": "11",
            "title": "Định lí và chứng minh định lí"
          },
          {
            "no": "OT3",
            "title": "Ôn tập chương III",
            "isReview": true
          }
        ]
      },
      {
        "no": "4",
        "roman": "IV",
        "title": "TAM GIÁC BẰNG NHAU",
        "lessons": [
          {
            "no": "12",
            "title": "Tổng các góc trong một tam giác"
          },
          {
            "no": "13",
            "title": "Hai tam giác bằng nhau. Trường hợp bằng nhau thứ nhất của tam giác"
          },
          {
            "no": "14",
            "title": "Trường hợp bằng nhau thứ hai và thứ ba của tam giác"
          },
          {
            "no": "15",
            "title": "Các trường hợp bằng nhau của tam giác vuông"
          },
          {
            "no": "16",
            "title": "Tam giác cân. Đường trung trực của đoạn thẳng"
          },
          {
            "no": "OT4",
            "title": "Ôn tập chương IV",
            "isReview": true
          }
        ]
      },
      {
        "no": "5",
        "roman": "V",
        "title": "THU THẬP VÀ BIỂU DIỄN DỮ LIỆU",
        "lessons": [
          {
            "no": "17",
            "title": "Thu thập và phân loại dữ liệu"
          },
          {
            "no": "18",
            "title": "Biểu đồ hình quạt tròn"
          },
          {
            "no": "19",
            "title": "Biểu đồ đoạn thẳng"
          },
          {
            "no": "OT5",
            "title": "Ôn tập chương V",
            "isReview": true
          }
        ]
      },
      {
        "no": "6",
        "roman": "VI",
        "title": "TỈ LỆ THỨC VÀ ĐẠI LƯỢNG TỈ LỆ",
        "lessons": [
          {
            "no": "20",
            "title": "Tỉ lệ thức"
          },
          {
            "no": "21",
            "title": "Tính chất của dãy tỉ số bằng nhau"
          },
          {
            "no": "22",
            "title": "Đại lượng tỉ lệ thuận"
          },
          {
            "no": "23",
            "title": "Đại lượng tỉ lệ nghịch"
          },
          {
            "no": "OT6",
            "title": "Ôn tập chương VI",
            "isReview": true
          }
        ]
      },
      {
        "no": "7",
        "roman": "VII",
        "title": "BIỂU THỨC ĐẠI SỐ VÀ ĐA THỨC MỘT BIẾN",
        "lessons": [
          {
            "no": "24",
            "title": "Biểu thức đại số"
          },
          {
            "no": "25",
            "title": "Đa thức một biến"
          },
          {
            "no": "26",
            "title": "Phép cộng và phép trừ đa thức một biến"
          },
          {
            "no": "27",
            "title": "Phép nhân đa thức một biến"
          },
          {
            "no": "28",
            "title": "Phép chia đa thức một biến"
          },
          {
            "no": "OT7",
            "title": "Ôn tập chương VII",
            "isReview": true
          }
        ]
      },
      {
        "no": "8",
        "roman": "VIII",
        "title": "LÀM QUEN VỚI BIẾN CỐ VÀ XÁC SUẤT CỦA BIẾN CỐ",
        "lessons": [
          {
            "no": "29",
            "title": "Làm quen với biến cố"
          },
          {
            "no": "30",
            "title": "Làm quen với xác suất của biến cố"
          },
          {
            "no": "OT8",
            "title": "Ôn tập chương VIII",
            "isReview": true
          }
        ]
      },
      {
        "no": "9",
        "roman": "IX",
        "title": "QUAN HỆ GIỮA CÁC YẾU TỐ TRONG MỘT TAM GIÁC",
        "lessons": [
          {
            "no": "31",
            "title": "Quan hệ giữa góc và cạnh đối diện trong một tam giác"
          },
          {
            "no": "32",
            "title": "Quan hệ giữa đường vuông góc và đường xiên"
          },
          {
            "no": "33",
            "title": "Quan hệ giữa ba cạnh của một tam giác"
          },
          {
            "no": "34",
            "title": "Sự đồng quy của ba đường trung tuyến, ba đường phân giác trong một tam giác"
          },
          {
            "no": "35",
            "title": "Sự đồng quy của ba đường trung trực, ba đường cao trong một tam giác"
          },
          {
            "no": "OT9",
            "title": "Ôn tập chương IX",
            "isReview": true
          }
        ]
      },
      {
        "no": "10",
        "roman": "X",
        "title": "MỘT SỐ HÌNH KHỐI TRONG THỰC TIỄN",
        "lessons": [
          {
            "no": "36",
            "title": "Hình hộp chữ nhật và hình lập phương"
          },
          {
            "no": "37",
            "title": "Hình lăng trụ đứng tam giác và hình lăng trụ đứng tứ giác"
          },
          {
            "no": "OT10",
            "title": "Ôn tập chương X",
            "isReview": true
          }
        ]
      }
    ]
  },
  "8": {
    "chapters": [
      {
        "no": "1",
        "roman": "I",
        "title": "ĐA THỨC",
        "lessons": [
          {
            "no": "1",
            "title": "Đơn thức"
          },
          {
            "no": "2",
            "title": "Đa thức"
          },
          {
            "no": "3",
            "title": "Phép cộng và phép trừ đa thức"
          },
          {
            "no": "4",
            "title": "Phép nhân đa thức"
          },
          {
            "no": "5",
            "title": "Phép chia đa thức cho đơn thức"
          },
          {
            "no": "OT1",
            "title": "Ôn tập chương I",
            "isReview": true
          }
        ]
      },
      {
        "no": "2",
        "roman": "II",
        "title": "HẰNG ĐẲNG THỨC ĐÁNG NHỚ VÀ ỨNG DỤNG",
        "lessons": [
          {
            "no": "6",
            "title": "Hiệu hai bình phương. Bình phương của một tổng hay một hiệu"
          },
          {
            "no": "7",
            "title": "Lập phương của một tổng hay một hiệu"
          },
          {
            "no": "8",
            "title": "Tổng và hiệu hai lập phương"
          },
          {
            "no": "9",
            "title": "Phân tích đa thức thành nhân tử"
          },
          {
            "no": "OT2",
            "title": "Ôn tập chương II",
            "isReview": true
          }
        ]
      },
      {
        "no": "3",
        "roman": "III",
        "title": "TỨ GIÁC",
        "lessons": [
          {
            "no": "10",
            "title": "Tứ giác"
          },
          {
            "no": "11",
            "title": "Hình thang cân"
          },
          {
            "no": "12",
            "title": "Hình bình hành"
          },
          {
            "no": "13",
            "title": "Hình chữ nhật"
          },
          {
            "no": "14",
            "title": "Hình thoi và hình vuông"
          },
          {
            "no": "OT3",
            "title": "Ôn tập chương III",
            "isReview": true
          }
        ]
      },
      {
        "no": "4",
        "roman": "IV",
        "title": "ĐỊNH LÍ THALÈS",
        "lessons": [
          {
            "no": "15",
            "title": "Định lí Thalès trong tam giác"
          },
          {
            "no": "16",
            "title": "Đường trung bình của tam giác"
          },
          {
            "no": "17",
            "title": "Tính chất đường phân giác của tam giác"
          },
          {
            "no": "OT4",
            "title": "Ôn tập chương IV",
            "isReview": true
          }
        ]
      },
      {
        "no": "5",
        "roman": "V",
        "title": "DỮ LIỆU VÀ BIỂU ĐỒ",
        "lessons": [
          {
            "no": "18",
            "title": "Thu thập và phân loại dữ liệu"
          },
          {
            "no": "19",
            "title": "Biểu diễn dữ liệu bằng bảng, biểu đồ"
          },
          {
            "no": "20",
            "title": "Phân tích số liệu thống kê dựa vào biểu đồ"
          },
          {
            "no": "OT5",
            "title": "Ôn tập chương V",
            "isReview": true
          }
        ]
      },
      {
        "no": "6",
        "roman": "VI",
        "title": "PHÂN THỨC ĐẠI SỐ",
        "lessons": [
          {
            "no": "21",
            "title": "Phân thức đại số"
          },
          {
            "no": "22",
            "title": "Tính chất cơ bản của phân thức đại số"
          },
          {
            "no": "23",
            "title": "Phép cộng và phép trừ phân thức đại số"
          },
          {
            "no": "24",
            "title": "Phép nhân và phép chia phân thức đại số"
          },
          {
            "no": "OT6",
            "title": "Ôn tập chương VI",
            "isReview": true
          }
        ]
      },
      {
        "no": "7",
        "roman": "VII",
        "title": "PHƯƠNG TRÌNH BẬC NHẤT VÀ HÀM SỐ BẬC NHẤT",
        "lessons": [
          {
            "no": "25",
            "title": "Phương trình bậc nhất một ẩn"
          },
          {
            "no": "26",
            "title": "Giải bài toán bằng cách lập phương trình"
          },
          {
            "no": "27",
            "title": "Khái niệm hàm số và đồ thị của hàm số"
          },
          {
            "no": "28",
            "title": "Hàm số bậc nhất và đồ thị của hàm số bậc nhất"
          },
          {
            "no": "29",
            "title": "Hệ số góc của đường thẳng"
          },
          {
            "no": "OT7",
            "title": "Ôn tập chương VII",
            "isReview": true
          }
        ]
      },
      {
        "no": "8",
        "roman": "VIII",
        "title": "MỞ ĐẦU VỀ TÍNH XÁC SUẤT CỦA BIẾN CỐ",
        "lessons": [
          {
            "no": "30",
            "title": "Kết quả có thể và kết quả thuận lợi"
          },
          {
            "no": "31",
            "title": "Cách tính xác suất của biến cố bằng tỉ số"
          },
          {
            "no": "32",
            "title": "Mối liên hệ giữa xác suất thực nghiệm với xác suất và ứng dụng"
          },
          {
            "no": "OT8",
            "title": "Ôn tập chương VIII",
            "isReview": true
          }
        ]
      },
      {
        "no": "9",
        "roman": "IX",
        "title": "TAM GIÁC ĐỒNG DẠNG",
        "lessons": [
          {
            "no": "33",
            "title": "Hai tam giác đồng dạng"
          },
          {
            "no": "34",
            "title": "Ba trường hợp đồng dạng của hai tam giác"
          },
          {
            "no": "35",
            "title": "Định lí Pythagore và ứng dụng"
          },
          {
            "no": "36",
            "title": "Các trường hợp đồng dạng của hai tam giác vuông"
          },
          {
            "no": "37",
            "title": "Hình đồng dạng"
          },
          {
            "no": "OT9",
            "title": "Ôn tập chương IX",
            "isReview": true
          }
        ]
      },
      {
        "no": "10",
        "roman": "X",
        "title": "MỘT SỐ HÌNH KHỐI TRONG THỰC TIỄN",
        "lessons": [
          {
            "no": "38",
            "title": "Hình chóp tam giác đều"
          },
          {
            "no": "39",
            "title": "Hình chóp tứ giác đều"
          },
          {
            "no": "OT10",
            "title": "Ôn tập chương X",
            "isReview": true
          }
        ]
      }
    ]
  },
  "9": {
    "chapters": [
      {
        "no": "1",
        "roman": "I",
        "title": "PHƯƠNG TRÌNH VÀ HỆ HAI PHƯƠNG TRÌNH BẬC NHẤT HAI ẨN",
        "lessons": [
          {
            "no": "1",
            "title": "Khái niệm phương trình và hệ hai phương trình bậc nhất hai ẩn"
          },
          {
            "no": "2",
            "title": "Giải hệ hai phương trình bậc nhất hai ẩn"
          },
          {
            "no": "3",
            "title": "Giải bài toán bằng cách lập hệ phương trình"
          },
          {
            "no": "OT1",
            "title": "Ôn tập chương I",
            "isReview": true
          }
        ]
      },
      {
        "no": "2",
        "roman": "II",
        "title": "PHƯƠNG TRÌNH VÀ BẤT PHƯƠNG TRÌNH BẬC NHẤT MỘT ẨN",
        "lessons": [
          {
            "no": "4",
            "title": "Phương trình quy về phương trình bậc nhất một ẩn"
          },
          {
            "no": "5",
            "title": "Bất đẳng thức và tính chất"
          },
          {
            "no": "6",
            "title": "Bất phương trình bậc nhất một ẩn"
          },
          {
            "no": "OT2",
            "title": "Ôn tập chương II",
            "isReview": true
          }
        ]
      },
      {
        "no": "3",
        "roman": "III",
        "title": "CĂN BẬC HAI VÀ CĂN BẬC BA",
        "lessons": [
          {
            "no": "7",
            "title": "Căn bậc hai và căn thức bậc hai"
          },
          {
            "no": "8",
            "title": "Khai căn bậc hai với phép nhân và phép chia"
          },
          {
            "no": "9",
            "title": "Biến đổi đơn giản và rút gọn biểu thức chứa căn thức bậc hai"
          },
          {
            "no": "10",
            "title": "Căn bậc ba và căn thức bậc ba"
          },
          {
            "no": "OT3",
            "title": "Ôn tập chương III",
            "isReview": true
          }
        ]
      },
      {
        "no": "4",
        "roman": "IV",
        "title": "HỆ THỨC LƯỢNG TRONG TAM GIÁC VUÔNG",
        "lessons": [
          {
            "no": "11",
            "title": "Tỉ số lượng giác của góc nhọn"
          },
          {
            "no": "12",
            "title": "Một số hệ thức giữa cạnh, góc trong tam giác vuông và ứng dụng"
          },
          {
            "no": "OT4",
            "title": "Ôn tập chương IV",
            "isReview": true
          }
        ]
      },
      {
        "no": "5",
        "roman": "V",
        "title": "ĐƯỜNG TRÒN",
        "lessons": [
          {
            "no": "13",
            "title": "Mở đầu về đường tròn"
          },
          {
            "no": "14",
            "title": "Cung và dây của một đường tròn"
          },
          {
            "no": "15",
            "title": "Độ dài của cung tròn. Diện tích hình quạt tròn và hình vành khuyên"
          },
          {
            "no": "16",
            "title": "Vị trí tương đối của đường thẳng và đường tròn"
          },
          {
            "no": "17",
            "title": "Vị trí tương đối của hai đường tròn"
          },
          {
            "no": "OT5",
            "title": "Ôn tập chương V",
            "isReview": true
          }
        ]
      },
      {
        "no": "6",
        "roman": "VI",
        "title": "HÀM SỐ y = ax² (a ≠ 0). PHƯƠNG TRÌNH BẬC HAI MỘT ẨN",
        "lessons": [
          {
            "no": "18",
            "title": "Hàm số y = ax² (a ≠ 0)"
          },
          {
            "no": "19",
            "title": "Phương trình bậc hai một ẩn"
          },
          {
            "no": "20",
            "title": "Định lí Viète và ứng dụng"
          },
          {
            "no": "21",
            "title": "Giải bài toán bằng cách lập phương trình"
          },
          {
            "no": "OT6",
            "title": "Ôn tập chương VI",
            "isReview": true
          }
        ]
      },
      {
        "no": "7",
        "roman": "VII",
        "title": "TẦN SỐ VÀ TẦN SỐ TƯƠNG ĐỐI",
        "lessons": [
          {
            "no": "22",
            "title": "Bảng tần số và biểu đồ tần số"
          },
          {
            "no": "23",
            "title": "Bảng tần số tương đối và biểu đồ tần số tương đối"
          },
          {
            "no": "24",
            "title": "Bảng tần số, tần số tương đối ghép nhóm và biểu đồ"
          },
          {
            "no": "OT7",
            "title": "Ôn tập chương VII",
            "isReview": true
          }
        ]
      },
      {
        "no": "8",
        "roman": "VIII",
        "title": "XÁC SUẤT CỦA BIẾN CỐ TRONG MỘT SỐ MÔ HÌNH XÁC SUẤT ĐƠN GIẢN",
        "lessons": [
          {
            "no": "25",
            "title": "Phép thử ngẫu nhiên và không gian mẫu"
          },
          {
            "no": "26",
            "title": "Xác suất của biến cố liên quan tới phép thử"
          },
          {
            "no": "OT8",
            "title": "Ôn tập chương VIII",
            "isReview": true
          }
        ]
      },
      {
        "no": "9",
        "roman": "IX",
        "title": "ĐƯỜNG TRÒN NGOẠI TIẾP VÀ ĐƯỜNG TRÒN NỘI TIẾP",
        "lessons": [
          {
            "no": "27",
            "title": "Góc nội tiếp"
          },
          {
            "no": "28",
            "title": "Đường tròn ngoại tiếp và đường tròn nội tiếp của một tam giác"
          },
          {
            "no": "29",
            "title": "Tứ giác nội tiếp"
          },
          {
            "no": "30",
            "title": "Đa giác đều"
          },
          {
            "no": "OT9",
            "title": "Ôn tập chương IX",
            "isReview": true
          }
        ]
      },
      {
        "no": "10",
        "roman": "X",
        "title": "MỘT SỐ HÌNH KHỐI TRONG THỰC TIỄN",
        "lessons": [
          {
            "no": "31",
            "title": "Hình trụ và hình nón"
          },
          {
            "no": "32",
            "title": "Hình cầu"
          },
          {
            "no": "OT10",
            "title": "Ôn tập chương X",
            "isReview": true
          }
        ]
      }
    ]
  },
  "10": {
    "chapters": [
      {
        "no": "1",
        "roman": "I",
        "title": "MỆNH ĐỀ VÀ TẬP HỢP",
        "lessons": [
          {
            "no": "1",
            "title": "Mệnh đề"
          },
          {
            "no": "2",
            "title": "Tập hợp và các phép toán trên tập hợp"
          },
          {
            "no": "OT1",
            "title": "Ôn tập chương I",
            "isReview": true
          }
        ]
      },
      {
        "no": "2",
        "roman": "II",
        "title": "BẤT PHƯƠNG TRÌNH VÀ HỆ BẤT PHƯƠNG TRÌNH BẬC NHẤT HAI ẨN",
        "lessons": [
          {
            "no": "3",
            "title": "Bất phương trình bậc nhất hai ẩn"
          },
          {
            "no": "4",
            "title": "Hệ bất phương trình bậc nhất hai ẩn"
          },
          {
            "no": "OT2",
            "title": "Ôn tập chương II",
            "isReview": true
          }
        ]
      },
      {
        "no": "3",
        "roman": "III",
        "title": "HỆ THỨC LƯỢNG TRONG TAM GIÁC",
        "lessons": [
          {
            "no": "5",
            "title": "Giá trị lượng giác của một góc từ 0° đến 180°"
          },
          {
            "no": "6",
            "title": "Hệ thức lượng trong tam giác"
          },
          {
            "no": "OT3",
            "title": "Ôn tập chương III",
            "isReview": true
          }
        ]
      },
      {
        "no": "4",
        "roman": "IV",
        "title": "VECTƠ",
        "lessons": [
          {
            "no": "7",
            "title": "Các khái niệm mở đầu"
          },
          {
            "no": "8",
            "title": "Tổng và hiệu của hai vectơ"
          },
          {
            "no": "9",
            "title": "Tích của một vectơ với một số"
          },
          {
            "no": "10",
            "title": "Vectơ trong mặt phẳng toạ độ"
          },
          {
            "no": "11",
            "title": "Tích vô hướng của hai vectơ"
          },
          {
            "no": "OT4",
            "title": "Ôn tập chương IV",
            "isReview": true
          }
        ]
      },
      {
        "no": "5",
        "roman": "V",
        "title": "CÁC SỐ ĐẶC TRƯNG CỦA MẪU SỐ LIỆU KHÔNG GHÉP NHÓM",
        "lessons": [
          {
            "no": "12",
            "title": "Số gần đúng và sai số"
          },
          {
            "no": "13",
            "title": "Các số đặc trưng đo xu thế trung tâm"
          },
          {
            "no": "14",
            "title": "Các số đặc trưng đo mức độ phân tán"
          },
          {
            "no": "OT5",
            "title": "Ôn tập chương V",
            "isReview": true
          }
        ]
      },
      {
        "no": "6",
        "roman": "VI",
        "title": "HÀM SỐ, ĐỒ THỊ VÀ ỨNG DỤNG",
        "lessons": [
          {
            "no": "15",
            "title": "Hàm số"
          },
          {
            "no": "16",
            "title": "Hàm số bậc hai"
          },
          {
            "no": "17",
            "title": "Dấu của tam thức bậc hai"
          },
          {
            "no": "18",
            "title": "Phương trình quy về phương trình bậc hai"
          },
          {
            "no": "OT6",
            "title": "Ôn tập chương VI",
            "isReview": true
          }
        ]
      },
      {
        "no": "7",
        "roman": "VII",
        "title": "PHƯƠNG PHÁP TOẠ ĐỘ TRONG MẶT PHẲNG",
        "lessons": [
          {
            "no": "19",
            "title": "Phương trình đường thẳng"
          },
          {
            "no": "20",
            "title": "Vị trí tương đối giữa hai đường thẳng. Góc và khoảng cách"
          },
          {
            "no": "21",
            "title": "Phương trình đường tròn"
          },
          {
            "no": "22",
            "title": "Ba đường conic"
          },
          {
            "no": "OT7",
            "title": "Ôn tập chương VII",
            "isReview": true
          }
        ]
      },
      {
        "no": "8",
        "roman": "VIII",
        "title": "ĐẠI SỐ TỔ HỢP",
        "lessons": [
          {
            "no": "23",
            "title": "Quy tắc đếm"
          },
          {
            "no": "24",
            "title": "Hoán vị, chỉnh hợp và tổ hợp"
          },
          {
            "no": "25",
            "title": "Nhị thức Newton"
          },
          {
            "no": "OT8",
            "title": "Ôn tập chương VIII",
            "isReview": true
          }
        ]
      },
      {
        "no": "9",
        "roman": "IX",
        "title": "TÍNH XÁC SUẤT THEO ĐỊNH NGHĨA CỔ ĐIỂN",
        "lessons": [
          {
            "no": "26",
            "title": "Biến cố và định nghĩa cổ điển của xác suất"
          },
          {
            "no": "27",
            "title": "Thực hành tính xác suất theo định nghĩa cổ điển"
          },
          {
            "no": "OT9",
            "title": "Ôn tập chương IX",
            "isReview": true
          }
        ]
      }
    ]
  },
  "11": {
    "chapters": [
      {
        "no": "1",
        "roman": "I",
        "title": "HÀM SỐ LƯỢNG GIÁC VÀ PHƯƠNG TRÌNH LƯỢNG GIÁC",
        "lessons": [
          {
            "no": "1",
            "title": "Giá trị lượng giác của góc lượng giác"
          },
          {
            "no": "2",
            "title": "Công thức lượng giác"
          },
          {
            "no": "3",
            "title": "Hàm số lượng giác"
          },
          {
            "no": "4",
            "title": "Phương trình lượng giác cơ bản"
          },
          {
            "no": "OT1",
            "title": "Ôn tập chương I",
            "isReview": true
          }
        ]
      },
      {
        "no": "2",
        "roman": "II",
        "title": "DÃY SỐ. CẤP SỐ CỘNG VÀ CẤP SỐ NHÂN",
        "lessons": [
          {
            "no": "5",
            "title": "Dãy số"
          },
          {
            "no": "6",
            "title": "Cấp số cộng"
          },
          {
            "no": "7",
            "title": "Cấp số nhân"
          },
          {
            "no": "OT2",
            "title": "Ôn tập chương II",
            "isReview": true
          }
        ]
      },
      {
        "no": "3",
        "roman": "III",
        "title": "CÁC SỐ ĐẶC TRƯNG ĐO XU THẾ TRUNG TÂM CỦA MẪU SỐ LIỆU GHÉP NHÓM",
        "lessons": [
          {
            "no": "8",
            "title": "Mẫu số liệu ghép nhóm"
          },
          {
            "no": "9",
            "title": "Các số đặc trưng đo xu thế trung tâm"
          },
          {
            "no": "OT3",
            "title": "Ôn tập chương III",
            "isReview": true
          }
        ]
      },
      {
        "no": "4",
        "roman": "IV",
        "title": "QUAN HỆ SONG SONG TRONG KHÔNG GIAN",
        "lessons": [
          {
            "no": "10",
            "title": "Đường thẳng và mặt phẳng trong không gian"
          },
          {
            "no": "11",
            "title": "Hai đường thẳng song song"
          },
          {
            "no": "12",
            "title": "Đường thẳng và mặt phẳng song song"
          },
          {
            "no": "13",
            "title": "Hai mặt phẳng song song"
          },
          {
            "no": "14",
            "title": "Phép chiếu song song"
          },
          {
            "no": "OT4",
            "title": "Ôn tập chương IV",
            "isReview": true
          }
        ]
      },
      {
        "no": "5",
        "roman": "V",
        "title": "GIỚI HẠN. HÀM SỐ LIÊN TỤC",
        "lessons": [
          {
            "no": "15",
            "title": "Giới hạn của dãy số"
          },
          {
            "no": "16",
            "title": "Giới hạn của hàm số"
          },
          {
            "no": "17",
            "title": "Hàm số liên tục"
          },
          {
            "no": "OT5",
            "title": "Ôn tập chương V",
            "isReview": true
          }
        ]
      },
      {
        "no": "6",
        "roman": "VI",
        "title": "HÀM SỐ MŨ VÀ HÀM SỐ LÔGARIT",
        "lessons": [
          {
            "no": "18",
            "title": "Luỹ thừa với số mũ thực"
          },
          {
            "no": "19",
            "title": "Lôgarit"
          },
          {
            "no": "20",
            "title": "Hàm số mũ và hàm số lôgarit"
          },
          {
            "no": "21",
            "title": "Phương trình, bất phương trình mũ và lôgarit"
          },
          {
            "no": "OT6",
            "title": "Ôn tập chương VI",
            "isReview": true
          }
        ]
      },
      {
        "no": "7",
        "roman": "VII",
        "title": "QUAN HỆ VUÔNG GÓC TRONG KHÔNG GIAN",
        "lessons": [
          {
            "no": "22",
            "title": "Hai đường thẳng vuông góc"
          },
          {
            "no": "23",
            "title": "Đường thẳng vuông góc với mặt phẳng"
          },
          {
            "no": "24",
            "title": "Phép chiếu vuông góc. Góc giữa đường thẳng và mặt phẳng"
          },
          {
            "no": "25",
            "title": "Hai mặt phẳng vuông góc"
          },
          {
            "no": "26",
            "title": "Khoảng cách"
          },
          {
            "no": "27",
            "title": "Thể tích"
          },
          {
            "no": "OT7",
            "title": "Ôn tập chương VII",
            "isReview": true
          }
        ]
      },
      {
        "no": "8",
        "roman": "VIII",
        "title": "CÁC QUY TẮC TÍNH XÁC SUẤT",
        "lessons": [
          {
            "no": "28",
            "title": "Biến cố hợp, biến cố giao, biến cố độc lập"
          },
          {
            "no": "29",
            "title": "Công thức cộng xác suất"
          },
          {
            "no": "30",
            "title": "Công thức nhân xác suất cho hai biến cố độc lập"
          },
          {
            "no": "OT8",
            "title": "Ôn tập chương VIII",
            "isReview": true
          }
        ]
      },
      {
        "no": "9",
        "roman": "IX",
        "title": "ĐẠO HÀM",
        "lessons": [
          {
            "no": "31",
            "title": "Định nghĩa và ý nghĩa của đạo hàm"
          },
          {
            "no": "32",
            "title": "Các quy tắc tính đạo hàm"
          },
          {
            "no": "33",
            "title": "Đạo hàm cấp hai"
          },
          {
            "no": "OT9",
            "title": "Ôn tập chương IX",
            "isReview": true
          }
        ]
      }
    ]
  },
  "12": {
    "chapters": [
      {
        "no": "1",
        "roman": "I",
        "title": "ỨNG DỤNG ĐẠO HÀM ĐỂ KHẢO SÁT VÀ VẼ ĐỒ THỊ CỦA HÀM SỐ",
        "lessons": [
          {
            "no": "1",
            "title": "Tính đơn điệu và cực trị của hàm số"
          },
          {
            "no": "2",
            "title": "Giá trị lớn nhất và giá trị nhỏ nhất của hàm số"
          },
          {
            "no": "3",
            "title": "Đường tiệm cận của đồ thị hàm số"
          },
          {
            "no": "4",
            "title": "Khảo sát sự biến thiên và vẽ đồ thị của hàm số"
          },
          {
            "no": "5",
            "title": "Ứng dụng đạo hàm để giải quyết một số vấn đề thực tiễn"
          },
          {
            "no": "OT1",
            "title": "Ôn tập chương I",
            "isReview": true
          }
        ]
      },
      {
        "no": "2",
        "roman": "II",
        "title": "VECTƠ VÀ HỆ TOẠ ĐỘ TRONG KHÔNG GIAN",
        "lessons": [
          {
            "no": "6",
            "title": "Vectơ trong không gian"
          },
          {
            "no": "7",
            "title": "Hệ toạ độ trong không gian"
          },
          {
            "no": "8",
            "title": "Biểu thức toạ độ của các phép toán vectơ"
          },
          {
            "no": "OT2",
            "title": "Ôn tập chương II",
            "isReview": true
          }
        ]
      },
      {
        "no": "3",
        "roman": "III",
        "title": "CÁC SỐ ĐẶC TRƯNG ĐO MỨC ĐỘ PHÂN TÁN CỦA MẪU SỐ LIỆU GHÉP NHÓM",
        "lessons": [
          {
            "no": "9",
            "title": "Khoảng biến thiên và khoảng tứ phân vị"
          },
          {
            "no": "10",
            "title": "Phương sai và độ lệch chuẩn"
          },
          {
            "no": "OT3",
            "title": "Ôn tập chương III",
            "isReview": true
          }
        ]
      },
      {
        "no": "4",
        "roman": "IV",
        "title": "NGUYÊN HÀM VÀ TÍCH PHÂN",
        "lessons": [
          {
            "no": "11",
            "title": "Nguyên hàm"
          },
          {
            "no": "12",
            "title": "Tích phân"
          },
          {
            "no": "13",
            "title": "Ứng dụng hình học của tích phân"
          },
          {
            "no": "OT4",
            "title": "Ôn tập chương IV",
            "isReview": true
          }
        ]
      },
      {
        "no": "5",
        "roman": "V",
        "title": "PHƯƠNG PHÁP TOẠ ĐỘ TRONG KHÔNG GIAN",
        "lessons": [
          {
            "no": "14",
            "title": "Phương trình mặt phẳng"
          },
          {
            "no": "15",
            "title": "Phương trình đường thẳng trong không gian"
          },
          {
            "no": "16",
            "title": "Công thức tính góc trong không gian"
          },
          {
            "no": "17",
            "title": "Phương trình mặt cầu"
          },
          {
            "no": "OT5",
            "title": "Ôn tập chương V",
            "isReview": true
          }
        ]
      },
      {
        "no": "6",
        "roman": "VI",
        "title": "XÁC SUẤT CÓ ĐIỀU KIỆN. QUY TẮC BAYES",
        "lessons": [
          {
            "no": "18",
            "title": "Xác suất có điều kiện"
          },
          {
            "no": "19",
            "title": "Công thức xác suất toàn phần và công thức Bayes"
          },
          {
            "no": "OT6",
            "title": "Ôn tập chương VI",
            "isReview": true
          }
        ]
      }
    ]
  }
};
